# General Settings
name: 'Zizzu.it'
title: 'Zizzu.it'
exclude: ['_themeforest*', 'Gemfile.lock', 'Gemfile']

job_title: consegne a domicilio dai negozi di zona
email: info@zizzu.it
shortdescription: Mappa aperta e gratuita per le consegne a domicilio dai negozi di zona
description: Aiutiamo Enti locali e Associazioni di categoria mettere online le adesioni degli esercizi commerciali che effettuano consegna a domicilio.<br>Forniamo strumenti per creare le mappe e un portale per le ricerche.<br/>Così, senza nessun secondo fine.
avatar: /assets/images/logo.png
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-162061850-1
disqus: zizzu


# Social Accounts
social_networks:
-  { name: facebook, url: 'https://facebook.com/zizzu.it' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/antonellopasella/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/zizzu-it' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: 'http://www.pasella.it' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 0
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://www.zizzu.it"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

